# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'MemoryManagementUI.ui'
#
# Created by: PyQt5 UI code generator 5.13.0
#
# WARNING! All changes made in this file will be lost!

import sys,time
from PyQt5 import QtCore, QtGui, QtWidgets
from threading import Thread, Lock
from MemoryManagement import MemoryManagementCore,generateInstructions


lock = Lock()

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(1121, 868)
        font = QtGui.QFont()
        font.setPointSize(15)
        MainWindow.setFont(font)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.label_3 = QtWidgets.QLabel(self.centralwidget)
        self.label_3.setGeometry(QtCore.QRect(300, 30, 78, 25))
        font = QtGui.QFont()
        font.setPointSize(15)
        self.label_3.setFont(font)
        self.label_3.setObjectName("label_3")
        self.label_4 = QtWidgets.QLabel(self.centralwidget)
        self.label_4.setGeometry(QtCore.QRect(480, 30, 78, 25))
        font = QtGui.QFont()
        font.setPointSize(15)
        self.label_4.setFont(font)
        self.label_4.setObjectName("label_4")
        self.label_5 = QtWidgets.QLabel(self.centralwidget)
        self.label_5.setGeometry(QtCore.QRect(650, 30, 78, 25))
        font = QtGui.QFont()
        font.setPointSize(15)
        self.label_5.setFont(font)
        self.label_5.setObjectName("label_5")
        self.label_6 = QtWidgets.QLabel(self.centralwidget)
        self.label_6.setGeometry(QtCore.QRect(800, 80, 65, 25))
        font = QtGui.QFont()
        font.setPointSize(15)
        self.label_6.setFont(font)
        self.label_6.setObjectName("label_6")
        self.label_7 = QtWidgets.QLabel(self.centralwidget)
        self.label_7.setGeometry(QtCore.QRect(800, 190, 52, 25))
        font = QtGui.QFont()
        font.setPointSize(15)
        self.label_7.setFont(font)
        self.label_7.setObjectName("label_7")
        self.label_8 = QtWidgets.QLabel(self.centralwidget)
        self.label_8.setGeometry(QtCore.QRect(140, 330, 195, 25))
        font = QtGui.QFont()
        font.setPointSize(15)
        self.label_8.setFont(font)
        self.label_8.setObjectName("label_8")
        self.label_9 = QtWidgets.QLabel(self.centralwidget)
        self.label_9.setGeometry(QtCore.QRect(440, 330, 273, 25))
        font = QtGui.QFont()
        font.setPointSize(15)
        self.label_9.setFont(font)
        self.label_9.setObjectName("label_9")
        self.label_10 = QtWidgets.QLabel(self.centralwidget)
        self.label_10.setGeometry(QtCore.QRect(780, 330, 234, 25))
        font = QtGui.QFont()
        font.setPointSize(15)
        self.label_10.setFont(font)
        self.label_10.setObjectName("label_10")
        self.label_11 = QtWidgets.QLabel(self.centralwidget)
        self.label_11.setGeometry(QtCore.QRect(10, 370, 65, 25))
        font = QtGui.QFont()
        font.setPointSize(15)
        self.label_11.setFont(font)
        self.label_11.setObjectName("label_11")
        self.label_12 = QtWidgets.QLabel(self.centralwidget)
        self.label_12.setGeometry(QtCore.QRect(10, 440, 52, 25))
        font = QtGui.QFont()
        font.setPointSize(15)
        self.label_12.setFont(font)
        self.label_12.setObjectName("label_12")
        self.label_13 = QtWidgets.QLabel(self.centralwidget)
        self.label_13.setGeometry(QtCore.QRect(910, 30, 143, 25))
        font = QtGui.QFont()
        font.setPointSize(15)
        self.label_13.setFont(font)
        self.label_13.setObjectName("label_13")
        self.label_2 = QtWidgets.QLabel(self.centralwidget)
        self.label_2.setGeometry(QtCore.QRect(130, 30, 78, 25))
        font = QtGui.QFont()
        font.setPointSize(15)
        self.label_2.setFont(font)
        self.label_2.setObjectName("label_2")
        self.layoutWidget = QtWidgets.QWidget(self.centralwidget)
        self.layoutWidget.setGeometry(QtCore.QRect(80, 80, 691, 221))
        self.layoutWidget.setObjectName("layoutWidget")
        self.gridLayout = QtWidgets.QGridLayout(self.layoutWidget)
        self.gridLayout.setContentsMargins(0, 0, 0, 0)
        self.gridLayout.setObjectName("gridLayout")
        self.lcdNumber_7 = QtWidgets.QLCDNumber(self.layoutWidget)
        font = QtGui.QFont()
        font.setPointSize(9)
        self.lcdNumber_7.setFont(font)
        self.lcdNumber_7.setObjectName("lcdNumber_7")
        self.gridLayout.addWidget(self.lcdNumber_7, 1, 2, 1, 1)
        self.lcdNumber_5 = QtWidgets.QLCDNumber(self.layoutWidget)
        font = QtGui.QFont()
        font.setPointSize(9)
        self.lcdNumber_5.setFont(font)
        self.lcdNumber_5.setObjectName("lcdNumber_5")
        self.gridLayout.addWidget(self.lcdNumber_5, 1, 0, 1, 1)
        self.lcdNumber_8 = QtWidgets.QLCDNumber(self.layoutWidget)
        font = QtGui.QFont()
        font.setPointSize(9)
        self.lcdNumber_8.setFont(font)
        self.lcdNumber_8.setObjectName("lcdNumber_8")
        self.gridLayout.addWidget(self.lcdNumber_8, 1, 3, 1, 1)
        self.lcdNumber_4 = QtWidgets.QLCDNumber(self.layoutWidget)
        font = QtGui.QFont()
        font.setPointSize(9)
        self.lcdNumber_4.setFont(font)
        self.lcdNumber_4.setObjectName("lcdNumber_4")
        self.gridLayout.addWidget(self.lcdNumber_4, 0, 3, 1, 1)
        self.lcdNumber = QtWidgets.QLCDNumber(self.layoutWidget)
        font = QtGui.QFont()
        font.setPointSize(9)
        self.lcdNumber.setFont(font)
        self.lcdNumber.setObjectName("lcdNumber")
        self.gridLayout.addWidget(self.lcdNumber, 0, 0, 1, 1)
        self.lcdNumber_3 = QtWidgets.QLCDNumber(self.layoutWidget)
        font = QtGui.QFont()
        font.setPointSize(9)
        self.lcdNumber_3.setFont(font)
        self.lcdNumber_3.setObjectName("lcdNumber_3")
        self.gridLayout.addWidget(self.lcdNumber_3, 0, 2, 1, 1)
        self.lcdNumber_6 = QtWidgets.QLCDNumber(self.layoutWidget)
        font = QtGui.QFont()
        font.setPointSize(9)
        self.lcdNumber_6.setFont(font)
        self.lcdNumber_6.setObjectName("lcdNumber_6")
        self.gridLayout.addWidget(self.lcdNumber_6, 1, 1, 1, 1)
        self.lcdNumber_2 = QtWidgets.QLCDNumber(self.layoutWidget)
        font = QtGui.QFont()
        font.setPointSize(9)
        self.lcdNumber_2.setFont(font)
        self.lcdNumber_2.setObjectName("lcdNumber_2")
        self.gridLayout.addWidget(self.lcdNumber_2, 0, 1, 1, 1)
        self.layoutWidget1 = QtWidgets.QWidget(self.centralwidget)
        self.layoutWidget1.setGeometry(QtCore.QRect(880, 80, 201, 221))
        self.layoutWidget1.setObjectName("layoutWidget1")
        self.gridLayout_2 = QtWidgets.QGridLayout(self.layoutWidget1)
        self.gridLayout_2.setContentsMargins(0, 0, 0, 0)
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.listWidget = QtWidgets.QListWidget(self.layoutWidget1)
        self.listWidget.setObjectName("listWidget")
        self.gridLayout_2.addWidget(self.listWidget, 0, 0, 1, 1)
        self.listWidget_2 = QtWidgets.QListWidget(self.layoutWidget1)
        self.listWidget_2.setObjectName("listWidget_2")
        self.gridLayout_2.addWidget(self.listWidget_2, 1, 0, 1, 1)
        self.layoutWidget2 = QtWidgets.QWidget(self.centralwidget)
        self.layoutWidget2.setGeometry(QtCore.QRect(90, 550, 661, 261))
        self.layoutWidget2.setObjectName("layoutWidget2")
        self.gridLayout_8 = QtWidgets.QGridLayout(self.layoutWidget2)
        self.gridLayout_8.setContentsMargins(0, 0, 0, 0)
        self.gridLayout_8.setObjectName("gridLayout_8")
        self.gridLayout_7 = QtWidgets.QGridLayout()
        self.gridLayout_7.setObjectName("gridLayout_7")
        self.listWidget_9 = QtWidgets.QListWidget(self.layoutWidget2)
        self.listWidget_9.setObjectName("listWidget_9")
        self.gridLayout_7.addWidget(self.listWidget_9, 0, 0, 1, 1)
        self.gridLayout_8.addLayout(self.gridLayout_7, 0, 0, 1, 1)
        self.listWidget_10 = QtWidgets.QListWidget(self.layoutWidget2)
        self.listWidget_10.setObjectName("listWidget_10")
        self.gridLayout_8.addWidget(self.listWidget_10, 0, 1, 1, 1)
        self.label_14 = QtWidgets.QLabel(self.centralwidget)
        self.label_14.setGeometry(QtCore.QRect(120, 510, 260, 25))
        font = QtGui.QFont()
        font.setPointSize(15)
        self.label_14.setFont(font)
        self.label_14.setObjectName("label_14")
        self.label_15 = QtWidgets.QLabel(self.centralwidget)
        self.label_15.setGeometry(QtCore.QRect(470, 510, 221, 25))
        font = QtGui.QFont()
        font.setPointSize(15)
        self.label_15.setFont(font)
        self.label_15.setObjectName("label_15")
        self.layoutWidget3 = QtWidgets.QWidget(self.centralwidget)
        self.layoutWidget3.setGeometry(QtCore.QRect(760, 550, 321, 261))
        self.layoutWidget3.setObjectName("layoutWidget3")
        self.gridLayout_9 = QtWidgets.QGridLayout(self.layoutWidget3)
        self.gridLayout_9.setContentsMargins(0, 0, 0, 0)
        self.gridLayout_9.setObjectName("gridLayout_9")
        self.pushButton_3 = QtWidgets.QPushButton(self.layoutWidget3)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.pushButton_3.setFont(font)
        self.pushButton_3.setObjectName("pushButton_3")
        self.gridLayout_9.addWidget(self.pushButton_3, 2, 0, 1, 1)
        self.pushButton = QtWidgets.QPushButton(self.layoutWidget3)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.pushButton.setFont(font)
        self.pushButton.setObjectName("pushButton")
        self.gridLayout_9.addWidget(self.pushButton, 0, 0, 1, 1)
        self.pushButton_2 = QtWidgets.QPushButton(self.layoutWidget3)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.pushButton_2.setFont(font)
        self.pushButton_2.setObjectName("pushButton_2")
        self.gridLayout_9.addWidget(self.pushButton_2, 1, 0, 1, 1)
        self.label = QtWidgets.QLabel(self.centralwidget)
        self.label.setGeometry(QtCore.QRect(230, 370, 39, 25))
        self.label.setObjectName("label")
        self.label_16 = QtWidgets.QLabel(self.centralwidget)
        self.label_16.setGeometry(QtCore.QRect(550, 370, 39, 25))
        self.label_16.setObjectName("label_16")
        self.label_17 = QtWidgets.QLabel(self.centralwidget)
        self.label_17.setGeometry(QtCore.QRect(860, 370, 100, 25))
        self.label_17.setObjectName("label_17")
        self.label_18 = QtWidgets.QLabel(self.centralwidget)
        self.label_18.setGeometry(QtCore.QRect(230, 440, 39, 25))
        self.label_18.setObjectName("label_18")
        self.label_19 = QtWidgets.QLabel(self.centralwidget)
        self.label_19.setGeometry(QtCore.QRect(550, 440, 39, 25))
        self.label_19.setObjectName("label_19")
        self.label_20 = QtWidgets.QLabel(self.centralwidget)
        self.label_20.setGeometry(QtCore.QRect(860, 440, 100, 25))
        self.label_20.setObjectName("label_20")
        #MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 1121, 26))
        self.menubar.setObjectName("menubar")
        #MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        #MainWindow.setStatusBar(self.statusbar)
        self.flag=0
        #bind buttons
        self.pushButton.clicked.connect(self.generateSequence)
        self.pushButton_2.clicked.connect(self.singleStep)
        self.pushButton_3.clicked.connect(self.goToEnd)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.label_3.setText(_translate("MainWindow", "Block2"))
        self.label_4.setText(_translate("MainWindow", "Block3"))
        self.label_5.setText(_translate("MainWindow", "Block4"))
        self.label_6.setText(_translate("MainWindow", "FIFO:"))
        self.label_7.setText(_translate("MainWindow", "LRU:"))
        self.label_8.setText(_translate("MainWindow", "Number Of Pages"))
        self.label_9.setText(_translate("MainWindow", "Number Of Page Faults"))
        self.label_10.setText(_translate("MainWindow", "Rate Of Page Fault"))
        self.label_11.setText(_translate("MainWindow", "FIFO:"))
        self.label_12.setText(_translate("MainWindow", "LRU:"))
        self.label_13.setText(_translate("MainWindow", "Page Status"))
        self.label_2.setText(_translate("MainWindow", "Block1"))
        self.label_14.setText(_translate("MainWindow", "Instruction Sequence"))
        self.label_15.setText(_translate("MainWindow", "Instruction pages"))
        self.pushButton_3.setText(_translate("MainWindow", "Go To End"))
        self.pushButton.setText(_translate("MainWindow", "Generate Instruction Sequence"))
        self.pushButton_2.setText(_translate("MainWindow", "Step By Step"))
        self.label.setText(_translate("MainWindow", "000"))
        self.label_16.setText(_translate("MainWindow", "000"))
        self.label_17.setText(_translate("MainWindow", "00.0%"))
        self.label_18.setText(_translate("MainWindow", "000"))
        self.label_19.setText(_translate("MainWindow", "000"))
        self.label_20.setText(_translate("MainWindow", "00.0%"))

    def generateSequence(self):
        self.stepCounter = 0
        self.flag=1
        memoryManagement.blockPage=[[-1 for i in range(4)] for i in range(2)]
        memoryManagement.blockFIFOQueue=[-1]*320
        memoryManagement.queueHead=0
        memoryManagement.queueCurrent=0
        memoryManagement.blockLRUSignal=[0]*4
        memoryManagement.pageNumber=[0]*2
        memoryManagement.pageFaultNumber=[0]*2
        memoryManagement.pageStaus1=[]
        memoryManagement.pageStaus2=[]
        self.instructions, self.pages = generateInstructions()
        self.listWidget_9.clear()
        self.listWidget_10.clear()
        self.listWidget.clear()
        self.listWidget_2.clear()
        self.label.setText("000")
        self.label_16.setText("000")
        self.label_17.setText("00.0%")
        self.label_18.setText("000")
        self.label_19.setText("000")
        self.label_20.setText("00.0%")
        self.lcdNumber.display(-1)
        self.lcdNumber_2.display(-1)
        self.lcdNumber_3.display(-1)
        self.lcdNumber_4.display(-1)
        self.lcdNumber_5.display(-1)
        self.lcdNumber_6.display(-1)
        self.lcdNumber_7.display(-1)
        self.lcdNumber_8.display(-1)
        for i in self.instructions:
            self.listWidget_9.addItem(str(i))
        for i in self.pages:
            self.listWidget_10.addItem(str(i))

    def singleStep(self):
        if self.flag==1 and self.stepCounter<=319:
            newPage = self.pages[self.stepCounter]
            memoryManagement.algorithmFIFO(newPage)
            memoryManagement.algorithmLRU(newPage)
            self.listWidget_9.setCurrentRow(self.stepCounter)
            self.listWidget_10.setCurrentRow(self.stepCounter)
            self.stepCounter += 1
            self.refreshDisplay()

    def ToEnd(self):
        while self.stepCounter <= 319:
            lock.acquire()
            self.singleStep()
            lock.release()
            time.sleep(0.1) 
            
    def goToEnd(self):
        if self.flag==1:
            t0 = Thread(target=self.ToEnd,args=())
            t0.start()

    def refreshDisplay(self):
        self.lcdNumber.display(memoryManagement.blockPage[0][0])
        self.lcdNumber_2.display(memoryManagement.blockPage[0][1])
        self.lcdNumber_3.display(memoryManagement.blockPage[0][2])
        self.lcdNumber_4.display(memoryManagement.blockPage[0][3])
        self.lcdNumber_5.display(memoryManagement.blockPage[1][0])
        self.lcdNumber_6.display(memoryManagement.blockPage[1][1])
        self.lcdNumber_7.display(memoryManagement.blockPage[1][2])
        self.lcdNumber_8.display(memoryManagement.blockPage[1][3])
        self.label.setText(str(memoryManagement.pageNumber[0]))
        self.label_16.setText(str(memoryManagement.pageFaultNumber[0]))
        self.label_17.setText(str(round((100*memoryManagement.pageFaultNumber[0]/memoryManagement.pageNumber[0]),2))+ '%')
        self.label_18.setText(str(memoryManagement.pageNumber[1]))
        self.label_19.setText(str(memoryManagement.pageFaultNumber[1]))
        self.label_20.setText(str(round((100*memoryManagement.pageFaultNumber[1]/memoryManagement.pageNumber[1]),2))+ '%')
        self.listWidget.addItem(memoryManagement.pageStaus1[self.stepCounter-1])
        self.listWidget_2.addItem(memoryManagement.pageStaus2[self.stepCounter-1])
        self.listWidget.setCurrentRow(self.stepCounter-1)
        self.listWidget_2.setCurrentRow(self.stepCounter-1)




if __name__ == '__main__':
    app = QtWidgets.QApplication(sys.argv)
    widget = QtWidgets.QWidget()
    ui = Ui_MainWindow()
    memoryManagement= MemoryManagementCore()

    ui.setupUi(widget)
    widget.show()

    sys.exit(app.exec_())